import pandas as pd
import sys

localrules: all, clean
wildcard_constraints:
    model_run="\d+"

#Benfiles, = glob_wildcards("Beninrun/output/{file}.txt")
#Kenfiles, = glob_wildcards("Kenyarun/output/{file}.txt")

MODELRUNS_Benin = range(150)
#MODELRUNS_Kenya = range(len(Kenfiles))


onstart:
    print('Checking user inputs...')

onsuccess:
    print('Workflow finished successfully!')

rule all:
    input:
        expand("Beninrun/output/Beninsample_{model_runs}.txt", model_runs=MODELRUNS_Benin)

rule build_DD:
    output:
        "Beninrun/output/Beninsample_{model_runs}.txt"
    log:
        "Beninrun/temp/{model_runs}.log"
    shell:
        "python scenariobuilder.py 'Benin' > {log}"
