import pandas as pd
import sys

localrules: all, clean
wildcard_constraints:
    #result_file="[^(objective)][a-zA-Z_\-]+",  ##Maybe not
    model_run="\d+"

#files, = glob_wildcards("Benin_run/output/{file}.txt")

#DDfiles = [pd.read_csv("run/output/{file}.txt") for file in files]
MODELRUNS = range(150)

onstart:
    print('Checking user inputs...')

onsuccess:
    print('Workflow finished successfully!')

rule all:
    input:
        expand("Kenya_run/output/Kenyasample_{model_runs}.txt", model_runs=MODELRUNS)


rule build_scenarios:
    message: "building DD-files"
    output:
        "Kenya_run/output/Kenyasample_{model_runs}.txt"
    shell:
        "python scenariobuilder.py 'Kenya'"